name: 'open-sauced-semantic-config-test'
description: 'Run @open-sauced/semantic-release-conventional-config on a repo'
branding:
  icon: 'package'
  color: 'yellow'
inputs:
  github-token:
    description: 'Github token for pushing releases'
    required: true
    default: ''
  dry-run:
    description: 'Skip publishing'
    required: false
    default: 'false'
outputs:
  released-version:
    description: 'The version that was released (empty if no release occured)'
  released-version-number:
    description: 'The version number (without a leading v) that was released (empty if no release occured)'
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: 'main.sh'
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
    DRY_RUN: ${{ inputs.dry-run }}
